// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0r7HUBlaYDlXn5n-8eCgavHxwRJbxu4',
    appId: '1:606244576139:web:aeff36ff85014219dbed8e',
    messagingSenderId: '606244576139',
    projectId: 'dikonda-hinduconnect',
    authDomain: 'dikonda-hinduconnect.firebaseapp.com',
    storageBucket: 'dikonda-hinduconnect.firebasestorage.app',
    measurementId: 'G-FVKJBFX0KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rHS0ScLeiTrHHN_NlVeAUdVxH8gM08g',
    appId: '1:606244576139:android:72772a4871cc2d76dbed8e',
    messagingSenderId: '606244576139',
    projectId: 'dikonda-hinduconnect',
    storageBucket: 'dikonda-hinduconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDN_nX44jDl0qY39QRNzASsraGnRPyxD0',
    appId: '1:606244576139:ios:b1f776be4b4741a6dbed8e',
    messagingSenderId: '606244576139',
    projectId: 'dikonda-hinduconnect',
    storageBucket: 'dikonda-hinduconnect.firebasestorage.app',
    iosBundleId: 'com.dikonda.hinduconnect',
  );

}